# Generated by Django 5.0.6 on 2024-05-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_email_receipents_delete_receipent'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='receipent',
            field=models.CharField(default='', max_length=200),
        ),
    ]
