# Generated by Django 5.0.6 on 2024-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_email_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachment',
            field=models.FilePathField(default='', path='./files_storage/'),
            preserve_default=False,
        ),
    ]
