# Generated by Django 5.0.6 on 2024-05-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_email_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachment',
            field=models.FileField(upload_to='settings.FILE_PATH_FIELD_DIRECTORY'),
        ),
    ]
